version: '3.4'

services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: quizpass
      TZ: 'Asia/Tokyo'
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    command: redis-server --appendonly yes
    networks:
      - default

  app:
    build: ./app
    container_name: app
    command: sh -c "sleep 10; python manage.py makemigrations; python manage.py migrate; python manage.py collectstatic --noinput; nohup gunicorn quizproject.wsgi -b 0.0.0.0:8000 &amp; daphne -b 0.0.0.0 -p 8001 quizproject.asgi:application"
    restart: always
    expose:
      - "8000"
      - "8001"
    volumes:
      - ./src:/webapp
      - static:/var/www/static
      - ./static:/var/www/static
    depends_on:
      - db
      - redis
    networks:
      - default

  web:
    image: nginx:latest
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - static:/var/www/static
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - ./web/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
    depends_on:
      - app
    networks:
      - default

volumes:
  static:
  public-data:
  tmp-data:
  db-data:

networks:
  default: